version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel_app_php8.1
    container_name: timecard_app
    restart: unless-stopped
    tty: true
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: timecard
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - ./backend:/var/www
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vuejs_app
    container_name: vuejs_frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

  # db:
  #   image: mysql:5.7
  #   container_name: mysql_db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: 'timecard'
  #     MYSQL_USER: 'root'
  #     MYSQL_PASSWORD: ''
  #     MYSQL_ROOT_PASSWORD: ''
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge
