version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app_php8.1
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: timecard
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - ./:/var/www
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
